### ISSUE TITLE
I encountered an error while evaluating

### ISSUE THREAD

**Issue by zty292** [nelson1425/EfficientAD#37]
(EfficientAD) E:\PycharmProjects\EfficientAD-main>python mvtec_ad_evaluation/evaluate_experiment.py --dataset_base_dir E:\Dataset\anomaly_detection\mvtec_anomaly_detection\mvtec_anomaly_detection\ --anomaly_maps_dir E:\PycharmProjects\EfficientAD-main\output\1\anomaly_maps\mvtec_ad --output_dir E:\PycharmProjects\EfficientAD-main\output\1\metrics/mvtec_ad --
evaluated_objects bottle
=== Evaluate bottle ===
Parsed 83 ground truth image files.
Read ground truth files and corresponding predictions...
  0%|                                                                                           | 0/83 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "E:\PycharmProjects\EfficientAD-main\mvtec_ad_evaluation\evaluate_experiment.py", line 247, in <module>
    main()
  File "E:\PycharmProjects\EfficientAD-main\mvtec_ad_evaluation\evaluate_experiment.py", line 215, in main
    calculate_au_pro_au_roc(
  File "E:\PycharmProjects\EfficientAD-main\mvtec_ad_evaluation\evaluate_experiment.py", line 148, in calculate_au_pro_au_roc
    prediction = util.read_tiff(pred_name)
  File "E:\PycharmProjects\EfficientAD-main\mvtec_ad_evaluation\generic_util.py", line 105, in read_tiff
    raise IOError('Found multiple files with a TIFF extension at'
OSError: Found multiple files with a TIFF extension at E:\PycharmProjects\EfficientAD-main\output\1\anomaly_maps\mvtec_ad\bottle\test\broken_large\000
Please specify which TIFF extension to use via the `exts` parameter of this function.

**Comment by HoseinHashemi** [comment]
Pass the argument `exts=['.tiff']` to the `util.read_tiff(pred_name)` and it must solve the issue.
So line 148 of evaluate_experiment.py should look like :  `prediction = util.read_tiff(pred_name, exts=['.tiff'])`

Or alternatively, the function could be changed to deal with the issue.
