### ISSUE TITLE
Error when evaluate with MVTec code

### ISSUE THREAD

**Issue by winstonchu498** [nelson1425/EfficientAD#42]
I used the python script you gave as follow:

`python mvtec_ad_evaluation/evaluate_experiment.py --dataset_base_dir './mvtec_anomaly_detection/' --anomaly_maps_dir './output/1/anomaly_maps/mvtec_ad/' --output_dir './output/1/metrics/mvtec_ad/' --evaluated_objects bottle`

but there are errors:

`python mvtec_ad_evaluation/evaluate_experiment.py --dataset_base_dir './mvtec_anomaly_detection/' --anomaly_maps_dir './output/1/anomaly_maps/mvtec_ad/' --output_dir './output/1/metrics/mvtec_ad/' --evaluated_objects bottle
=== Evaluate bottle ===
Parsed 83 ground truth image files.
Read ground truth files and corresponding predictions...
  0%|                                                                                                                                                                                  | 0/83 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "F:\implementation_anomalydetection\nelson1425_EfficientAD\nelson_data\mvtec_ad_evaluation\evaluate_experiment.py", line 247, in <module>
    main()
  File "F:\implementation_anomalydetection\nelson1425_EfficientAD\nelson_data\mvtec_ad_evaluation\evaluate_experiment.py", line 215, in main
    calculate_au_pro_au_roc(
  File "F:\implementation_anomalydetection\nelson1425_EfficientAD\nelson_data\mvtec_ad_evaluation\evaluate_experiment.py", line 148, in calculate_au_pro_au_roc
    prediction = util.read_tiff(pred_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\implementation_anomalydetection\nelson1425_EfficientAD\nelson_data\mvtec_ad_evaluation\generic_util.py", line 102, in read_tiff
    raise FileNotFoundError('Could not find a file with a TIFF extension'
FileNotFoundError: Could not find a file with a TIFF extension at ./output/1/anomaly_maps/mvtec_ad/bottle\test\broken_large\000
(base) PS F:\implementation_anomalydetection\nelson1425_EfficientAD\nelson_data>

`

all the mvtec_ad_evaluation.tar.xz and mvtec_anomaly_detection.tar.xz are from what you share.
I am running from aconda powershell from windows 10

can anyone point a way ?

**Comment by HoseinHashemi** [comment]
Pass the argument `exts=['.tiff']` to the `util.read_tiff(pred_name)` and it must solve the issue.
So line 148 of evaluate_experiment.py should look like :  `prediction = util.read_tiff(pred_name, exts=['.tiff'])`

Or alternatively, the function could be changed to deal with the issue.

**Comment by anewcatwhy** [comment]
> Pass the argument `exts=['.tiff']` to the `util.read_tiff(pred_name)` and it must solve the issue. So line 148 of evaluate_experiment.py should look like : `prediction = util.read_tiff(pred_name, exts=['.tiff'])`
> 
> Or alternatively, the function could be changed to deal with the issue.

excuse me ，i have the other question ：
  File "D:\all_zip\EfficientAD-main\mvtec_loco_ad_evaluation\evaluate_experiment.py", line 486, in <module>
    main()
  File "D:\all_zip\EfficientAD-main\mvtec_loco_ad_evaluation\evaluate_experiment.py", line 111, in main
    gt_maps, anomaly_maps = read_maps(
  File "D:\all_zip\EfficientAD-main\mvtec_loco_ad_evaluation\evaluate_experiment.py", line 195, in read_maps
    raise OSError(
OSError: Anomaly map good\000.tiff has no corresponding ground truth map, so it must be a good image. Good images must have a relative path starting with "good/"  (relative to the test dir at D:\all_zip\EfficientAD-main\output\4\anomaly_maps\mvtec_loco\breakfast_box\test)
i don't know how to solve it

**Comment by yufanfanwu-beep** [comment]
> 我用了你给出的Python脚本如下：
> 
> `python mvtec_ad_evaluation/evaluate_experiment.py --dataset_base_dir './mvtec_anomaly_detection/' --anomaly_maps_dir './output/1/anomaly_maps/mvtec_ad/' --output_dir './output/1/metrics/mvtec_ad/' --evaluated_objects bottle`
> 
> 但存在错误：
> 
> 'python mvtec_ad_evaluation/evaluate_experiment.py --dataset_base_dir './mvtec_anomaly_detection/' --anomaly_maps_dir './output/1/anomaly_maps/mvtec_ad/' --output_dir './output/1/metrics/mvtec_ad/' --evaluated_objects瓶 === 评估瓶 === 解析了83个真实图像文件。阅读真实数据和相应预测...... 0%| |0/83 [00：00<?, ?it/s] 回溯（最近一次通话）：文件“F：\implementation_anomalydetection\nelson1425_EfficientAD\nelson_data\mvtec_ad_evaluation\evaluate_experiment.py”，主文件（）中第247行，主文件“F：\implementation_anomalydetection\nelson1425_EfficientAD\nelson_data\mvtec_ad_evaluation\evaluate_experiment.py”，主calculate_au_pro_au_roc中第215行（文件“F：\implementation_anomalydetection\nelson1425_EfficientAD\nelson_data\mvtec_ad_evaluation\evaluate_experiment.py”，第148行，calculate_au_pro_au_roc预测=util.read_tiff（pred_name） ^^^^^^^^^^^^^^^^^^^^^^^^^ 文件“F：\implementation_anomalydetection\nelson1425_EfficientAD\nelson_data\mvtec_ad_evaluation\generic_util.py”，文件“第102行，read_tiff 提出 FileNotFoundError（'找不到带有TIFF的文件扩展名' FileNotFoundError：找不到带有 TIFF 扩展名的文件，地址为 ./output/1/anomaly_maps/mvtec_ad/bottle\test\broken_large\000（基础） PS F：\implementation_anomalydetection\nelson1425_EfficientAD\nelson_data>
> 
> `
> 
> 所有mvtec_ad_evaluation.tar.xz和mvtec_anomaly_detection.tar.xz都是你分享的内容。我使用的是Windows 10的Aconda PowerShell
> 
> 有人能指点一下吗？

Could you please tell me how you obtained "mvtec_loco_ad_evaluation.tar.xz"? I'm really looking forward to your reply, as it will be of great help to me.
